// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7rC4-HbG0p_7WhBgL2ib-L-kFLSCHXgk',
    appId: '1:1033276198160:web:2c943f1cdc53558b0ca995',
    messagingSenderId: '1033276198160',
    projectId: 'app-demo-18d55',
    authDomain: 'app-demo-18d55.firebaseapp.com',
    databaseURL: 'https://app-demo-18d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-demo-18d55.appspot.com',
    measurementId: 'G-64PG5FFRDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtM75YEjfg2K1a8fZl4QcF_lMqEn8WrAY',
    appId: '1:1033276198160:android:f7e918a0e42a49060ca995',
    messagingSenderId: '1033276198160',
    projectId: 'app-demo-18d55',
    databaseURL: 'https://app-demo-18d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-demo-18d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Xy2oIvuOT6nmG2UjmtPfx8Y4FsybNKE',
    appId: '1:1033276198160:ios:2f0a0c00509d85bd0ca995',
    messagingSenderId: '1033276198160',
    projectId: 'app-demo-18d55',
    databaseURL: 'https://app-demo-18d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-demo-18d55.appspot.com',
    androidClientId: '1033276198160-cfkhrb61016933mddma1mikrqtj8k3n9.apps.googleusercontent.com',
    iosClientId: '1033276198160-1g1bn90lhv0gh2fs4tor54j7jpi7dapd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7rC4-HbG0p_7WhBgL2ib-L-kFLSCHXgk',
    appId: '1:1033276198160:web:d98af6be9d2416550ca995',
    messagingSenderId: '1033276198160',
    projectId: 'app-demo-18d55',
    authDomain: 'app-demo-18d55.firebaseapp.com',
    databaseURL: 'https://app-demo-18d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'app-demo-18d55.appspot.com',
    measurementId: 'G-TT5Y0334BH',
  );
}
